### ISSUE TITLE
MkTechDocs cannot produce PDF files because it's out of step with Pandoc

### ISSUE THREAD

**Issue by johnblommers** [att/MkTechDocs#34]
It is not possible to generate a PDF anymore because MkTechDocs isn't passing the `--pdf-engine` command line option but instead is passing the no-longer working `--latex-engine` option.

Pandoc is presently at version 2.9.

Here's what happens:

```bash
mktechdocs
[+] Build environment looks good.
[+] Removing old temporary build files
[+] Removing old my_mktechdocs_project_pages (if it exists)
[+] Creating my_mktechdocs_project_pages for output
[+] Ignoring HTML_STYLE.
[+] Building main tex my_mktechdocs_project.tex
--latex-engine has been removed.  Use --pdf-engine instead.
Try pandoc --help for more information.
[+] Fixing floating diagrams to appear inline.
[+] Creating pdf, pass 1
[-] Command failed. Build stopped.
```

And this is the `mktechdoc.conf`  file:

```
TITLE="My MkTechDocs Project"
OUTPUT_FILE_NAME_BASE=my_mktechdocs_project
FORMAT=pdf
TABLE_OF_CONTENTS_MAIN_DEPTH=6
TABLE_OF_CONTENTS_SUB_DEPTH=3
SECTION_NUMBERS=true
KEEP_TEMP_FILES=true
```

The file `subdocument.md` is:

```
# Heading One

My markup goes here.

## Subheading 1

bla bla bla.

### Subheading 3

more bla bla
```

**Update**

A quick fix is to edit the Bash script `mktechdocs` at line 495 and replace `--latex-engine=xelatex` with `--pdf-engine=xelatex` That worked for me in  generating PDFs.

**Comment by jsseidel** [comment]
Thanks for the issue reports. Good to give this PDF stuff a workout. We don't use it much these days. Will fix up these issues.

**Comment by jsseidel** [comment]
Fix committed. Support added for 1.19+ (need to support this version because it's on 18.04 ubuntu) and 2.0+.
