### ISSUE TITLE
PDF production fails because \passthrough is undefined

### ISSUE THREAD

**Issue by johnblommers** [att/MkTechDocs#35]
When your source Markdown file contains `backticked text` then the `\passthrough` construct gets emitted. It's undefined so pass two of the PDF generation phase fails. 

The solution is to define it (as is done in Pandoc's [default.latex](https://github.com/jgm/pandoc-templates/blob/master/default.latex)) as follows in `/opt/mktechdocs/lib/template.tex` by adding the following lines after the `documentclass` statement:

```latex
$if(listings)$
\usepackage{listings}
\newcommand{\passthrough}[1]{#1}
\lstset{defaultdialect=[5.3]Lua}
\lstset{defaultdialect=[x86masm]Assembler}
$endif$
```

**Comment by jsseidel** [comment]
Fix committed. Support added for 1.19+ (need to support this version because it's on 18.04 ubuntu) and 2.0+.
